// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8IkwAFxwN2pbmP2Zs2dZYOj_dMmAkNiE',
    appId: '1:565070854281:web:65fb8d3b3851b44062ee58',
    messagingSenderId: '565070854281',
    projectId: 'project-map-86c81',
    authDomain: 'project-map-86c81.firebaseapp.com',
    databaseURL: 'https://project-map-86c81-default-rtdb.firebaseio.com',
    storageBucket: 'project-map-86c81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4o844e73O3hjixwUHyxdSWnRkYHcTfkg',
    appId: '1:565070854281:android:eeefc1c5bd43ff8e62ee58',
    messagingSenderId: '565070854281',
    projectId: 'project-map-86c81',
    databaseURL: 'https://project-map-86c81-default-rtdb.firebaseio.com',
    storageBucket: 'project-map-86c81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCQ7xaLrM_3eg44s6yaPeLc6TDiU2k3wo',
    appId: '1:565070854281:ios:f5dc51829702c7e262ee58',
    messagingSenderId: '565070854281',
    projectId: 'project-map-86c81',
    databaseURL: 'https://project-map-86c81-default-rtdb.firebaseio.com',
    storageBucket: 'project-map-86c81.appspot.com',
    iosBundleId: 'com.example.map',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCQ7xaLrM_3eg44s6yaPeLc6TDiU2k3wo',
    appId: '1:565070854281:ios:ef04154042e62ba262ee58',
    messagingSenderId: '565070854281',
    projectId: 'project-map-86c81',
    databaseURL: 'https://project-map-86c81-default-rtdb.firebaseio.com',
    storageBucket: 'project-map-86c81.appspot.com',
    iosBundleId: 'com.example.map.RunnerTests',
  );
}
